apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cfeai7b5e-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cfeai7b5e-go 
  name: cfeai7b5e-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cfeai7b5e-go 
